settings:
  title: 'Averdoc Status'
  url: 'https://status.averdoc.com' # used for Slack messages
  logo: 'https://www.averdoc.com/logo.svg' # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: webapi-averdoc-com # unique identifier
    name: API (asia-southeast1 region)
    description: 'Core API, Database, and storage.' # default=empty
    url: 'https://webapi.averdoc.com/api/live' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: false # allows the title to be a link, default=true
    
  - id: account-averdoc-com # unique identifier
    name: Authorization Server (asia-southeast1 region)
    description: 'Authorization Server and Account API' # default=empty
    url: 'https://account.averdoc.com/Account/Login/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: false # allows the title to be a link, default=true

  - id: app-averdoc-com
    name: Web Application (app.averdoc.com)
    description: 'Web Application'
    url: 'https://app.averdoc.com/'
    method: GET
    expectStatus: 200
    followRedirect: false
    linkable: false
    
  - id: www-averdoc-com
    name: www.averdoc.com
    description: 'Averdoc.com Website'
    url: 'https://www.averdoc.com/en/'
    method: GET
    expectStatus: 200
    linkable: true


